### PR TITLE
Improves Pipeline Configuration

### PR DESCRIPTION
**Pull request by mverteuil**
- Added retrieving the configuration XML for a pipeline, directly from the pipeline
- Exposed a method for deleting pipelines from the Admin class, simple delegation.

[Review on Reviewable](https://reviewable.io/reviews/joaogbcravo/gocdapi/10)

### CODE REVIEW

**Comment by joaogbcravo** [comment]
Hey @mverteuil 

Thanks for your PR. I know that it's a picky thing but the CI is failing. Can you fix it please?
If you want to turn '_poll_configuration' method public, I'm ok with it.

Cheers,
João

**Comment by mverteuil** [comment]
Aye, I agree with the linter issue and the suggested solution. I'll rework my commits. :+1:

**Comment by mverteuil** [comment]
@joaogbcravo I've fixed up my commits, it should pass now. :haircut:

**Comment by mverteuil** [comment]
Damnit, I'll fix the import too.

**Comment by mverteuil** [comment]
Import fixed! :hammer:

**Comment by joaogbcravo** [comment]
Thank you!

**Pull request merged**
